apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-deployment-deployment
  labels:
    app: purchase-deployment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase-deployment-service
  template:
    metadata:
      labels:
        app: purchase-deployment-service
    spec:
      containers:
        - name: purchase-deployment-service
          image: yurwar/purchase-deployment
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-deployment-service
spec:
  selector:
    app: purchase-deployment-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30012
  type: LoadBalancer
