apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: yurwar/search
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30013
  type: LoadBalancer
