apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-supplier-deployment
  labels:
    app: price-supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-supplier-service
  template:
    metadata:
      labels:
        app: price-supplier-service
    spec:
      containers:
        - name: price-supplier-service
          image: yurwar/price-supplier
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: price-supplier-service
spec:
  selector:
    app: price-supplier-service
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30011
  type: LoadBalancer
