apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
  labels:
    app: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
        - name: authorization-service
          image: yurwar/authorization
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  selector:
    app: authorization-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30008
  type: LoadBalancer
